url: http://greg.nokes.name
name: DaRoost
description: >
  A wayward journey into the depths of sanity

theme: jekflix
# Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://greg.nokes.name" # the base hostname & protocol for your site
z3google_analytics: "UA-XXXXXXXX-X"

# User Settings
#username: Jekflix
#user_description: Some text about you.
#disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: tsykoduk
#facebook_username: facebook_username
twitter_username: tsykoduk
#instagram_username: instagram_username
#linkedin_username: linkedin_username
#medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

plugins: ['kramdown','jemoji']
exclude: ['package.json', 'src', 'node_modules','config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile','to_be_cleaned']
